#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

####################
### Cluster Configuration
####################

# The cluster name this StreamNode belongs to
# cluster_name=defaultCluster

####################
### StreamNode RPC Configuration
####################

# The address that this StreamNode's RPC service listens on
# sn_internal_address=127.0.0.1

# The port that this StreamNode's internal RPC service listens on
# sn_internal_port=10820

# Max concurrent client connections for RPC
# sn_rpc_max_concurrent_client_num=1000

# Whether to enable Thrift compression for RPC
# sn_rpc_thrift_compression_enable=false

####################
### Seed ConfigNode Configuration
####################

# The seed ConfigNode that this StreamNode will register to (address:port)
# sn_seed_config_node=127.0.0.1:10710

####################
### Stream Task Execution Configuration
####################

# Number of threads for stream task execution
# sn_executor_thread_num=4
