# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Maven.gitlab-ci.yml

# Build JAVA applications using Apache Maven (http://maven.apache.org)
# For docker image tags see https://hub.docker.com/_/maven/
#
# For general lifecycle information see https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html

# This template will build and test your projects
# * Caches downloaded dependencies and plugins between invocation.
# * Verify but don't deploy merge requests.
# * Deploy built artifacts from master branch only.

default:
  timeout: 5h

variables:
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  NO_PROXY: "localhost,127.0.0.1,10.180.34.0/24,192.168.134.0/24,192.168.135.0/24"
  no_proxy: "localhost,127.0.0.1,10.180.34.0/24,192.168.134.0/24,192.168.135.0/24"

# This template uses the latest Maven 3 release, e.g., 3.8.6, and OpenJDK 8 (LTS)
# for verifying and deploying images
# Maven 3.8.x REQUIRES HTTPS repositories.
# See https://maven.apache.org/docs/3.8.1/release-notes.html#how-to-fix-when-i-get-a-http-repository-blocked for more.
image:
  name: maven:3.9.14-eclipse-temurin-17-lsof
  pull_policy: never

stages:
  - .pre
  - test
  - cd
  - sonarqube-check

before_script:
  - echo "127.0.0.1 $(hostname) localhost" >> /etc/hosts
  - grep -rlZ "\u0000" ~/.m2 | xargs -0 -I {} rm -fv {} || true

unit-test:
  stage: test
  tags:
    - hybrid-db

  script:
    - 'mvn clean install -Dtest.port.closed=true'
  interruptible: true
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH 
        || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rel/ 
        || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rc/
        || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "queryStage"
        || $CI_PIPELINE_SOURCE == "schedule"

streamnode-integration-test:
  stage: test
  tags:
    - hybrid-db
  script:
    - 'mvn -T16 -pl iotdb-core/streamnode -am -DskipITs -Drat.skip=true -Dsurefire.failIfNoSpecifiedTests=false -Dtest=StreamTaskManagerTest,StreamTaskSchedulerTest,StreamTaskSchedulerIntegrationTest,StreamTaskInstanceTest,StreamSubTaskTest,WriteBackEngineTest,PartitionKeyTest,StreamTaskSerializationTest,ColumnPartitionedTabletDispatcherTest,IoTDBSubscriptionSourceInstanceTest,PlaceholderReplacerTest test'
    - 'mvn -T16 clean verify -P with-integration-tests -P SimpleIT -DskipUTs -DfailIfNoTests=false -Dfailsafe.failIfNoSpecifiedTests=false -Dit.test=IoTDBSubscriptionSourceInstanceIT,StreamNodeManualRuntimeAssemblyIT,StreamSqlMetadataIT,StreamTaskInstanceIT -DConfigNodeMaxHeapSize=1024 -DDataNodeMaxHeapSize=1024 -pl integration-test -am'
  interruptible: true
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "queryStage"
  artifacts:
    when: on_failure
    name: streamnode-it-log
    paths:
      - integration-test/target/cluster-logs
    expire_in: 7 day

integration-test-1c1d:
  stage: test
  tags:
    - hybrid-db
  script:
    - 'mvn verify -P with-integration-tests -P SimpleIT -DskipUTs -DintegrationTest.forkCount=8 -DConfigNodeMaxHeapSize=1024 -DDataNodeMaxHeapSize=1024 -pl integration-test -am'
  interruptible: true
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH 
        || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rel/ 
        || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rc/
        || $CI_PIPELINE_SOURCE == "schedule"
  artifacts:
    when: on_failure
    name: 1c1d-log
    paths:
      - integration-test/target/cluster-logs
    expire_in: 7 day


integration-test-1c3d:
  stage: test
  tags:
    - hybrid-db
  script:
    - 'mvn verify -P with-integration-tests -DskipUTs -DintegrationTest.forkCount=6 -DConfigNodeMaxHeapSize=1024 -DDataNodeMaxHeapSize=1024 -pl integration-test -am -PClusterIT'
  interruptible: true
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH 
        || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rel/ 
        || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rc/
        || $CI_PIPELINE_SOURCE == "schedule"
  artifacts:
    when: on_failure
    name: 1c3d-log
    paths:
      - integration-test/target/cluster-logs
    expire_in: 7 day

table-integration-test-1c1d:
  stage: test
  tags:
    - hybrid-db
  script:
    - 'mvn verify -P with-integration-tests -DskipUTs -DintegrationTest.forkCount=8 -DConfigNodeMaxHeapSize=1024 -DDataNodeMaxHeapSize=1024 -pl integration-test -am -PTableSimpleIT'
  interruptible: true
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH 
        || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rel/ 
        || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rc/
        || $CI_PIPELINE_SOURCE == "schedule"
  artifacts:
    when: on_failure
    name: 1c1d-log
    paths:
      - integration-test/target/cluster-logs
    expire_in: 7 day


table-integration-test-1c3d:
  stage: test
  tags:
    - hybrid-db
  script:
    - 'mvn verify -P with-integration-tests -DskipUTs -DintegrationTest.forkCount=6 -DConfigNodeMaxHeapSize=1024 -DDataNodeMaxHeapSize=1024 -pl integration-test -am -PTableClusterIT'
  interruptible: true
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH 
        || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rel/ 
        || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rc/
        || $CI_PIPELINE_SOURCE == "schedule"
  artifacts:
    when: on_failure
    name: 1c3d-log
    paths:
      - integration-test/target/cluster-logs
    expire_in: 7 day

pipe-single:
  stage: test
  tags:
    - hybrid-db
  script:
    - 'mvn clean verify -P with-integration-tests -DskipUTs -DintegrationTest.forkCount=1 -DConfigNodeMaxHeapSize=256 -DDataNodeMaxHeapSize=768 -DClusterConfigurations=$CLUSTER1,$CLUSTER2 -pl integration-test -am -PMultiClusterIT1'
  parallel:
    matrix:
      - CLUSTER1: [HighPerformanceMode]
        CLUSTER2: [HighPerformanceMode]
  interruptible: true
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH 
        || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rel/ 
        || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rc/
        || $CI_PIPELINE_SOURCE == "schedule"
  artifacts:
    when: on_failure
    name: pipe-log-single
    paths:
      - integration-test/target/cluster-logs
      - integration-test/target/pipeIT-logs
    expire_in: 7 day

pipe-dual-tree-auto-basic:
  stage: test
  tags:
    - hybrid-db
  script:
    - 'mvn clean verify -P with-integration-tests -DskipUTs -DintegrationTest.forkCount=1 -DConfigNodeMaxHeapSize=256 -DDataNodeMaxHeapSize=768 -DClusterConfigurations=$CLUSTER1,$CLUSTER2 -pl integration-test -am -PMultiClusterIT2DualTreeAutoBasic'
  parallel:
    matrix:
      - CLUSTER1: [HighPerformanceMode]
        CLUSTER2: [HighPerformanceMode]
  interruptible: true
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH 
        || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rel/ 
        || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rc/
        || $CI_PIPELINE_SOURCE == "schedule"
  artifacts:
    when: on_failure
    name: pipe-log-dual-tree-auto-basic
    paths:
      - integration-test/target/cluster-logs
      - integration-test/target/pipeIT-logs
    expire_in: 7 day

pipe-dual-tree-auto-enhanced:
  stage: test
  tags:
    - hybrid-db
  script:
    - 'mvn clean verify -P with-integration-tests -DskipUTs -DintegrationTest.forkCount=1 -DConfigNodeMaxHeapSize=256 -DDataNodeMaxHeapSize=768 -DClusterConfigurations=$CLUSTER1,$CLUSTER2 -pl integration-test -am -PMultiClusterIT2DualTreeAutoEnhanced'
  parallel:
    matrix:
      - CLUSTER1: [HighPerformanceMode]
        CLUSTER2: [HighPerformanceMode]
  interruptible: true
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH 
        || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rel/ 
        || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rc/
        || $CI_PIPELINE_SOURCE == "schedule"
  artifacts:
    when: on_failure
    name: pipe-log-dual-tree-auto-enhanced
    paths:
      - integration-test/target/cluster-logs
      - integration-test/target/pipeIT-logs
    expire_in: 7 day

pipe-dual-tree-manual:
  stage: test
  tags:
    - hybrid-db
  script:
    - 'mvn clean verify -P with-integration-tests -DskipUTs -DintegrationTest.forkCount=1 -DConfigNodeMaxHeapSize=256 -DDataNodeMaxHeapSize=768 -DClusterConfigurations=$CLUSTER1,$CLUSTER2 -pl integration-test -am -PMultiClusterIT2DualTreeManual'
  parallel:
    matrix:
      - CLUSTER1: [HighPerformanceMode]
        CLUSTER2: [HighPerformanceMode]
  interruptible: true
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH 
        || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rel/ 
        || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rc/
        || $CI_PIPELINE_SOURCE == "schedule"
  artifacts:
    when: on_failure
    name: pipe-log-dual-tree-manual
    paths:
      - integration-test/target/cluster-logs
      - integration-test/target/pipeIT-logs
    expire_in: 7 day

pipe-dual-table-manual-basic:
  stage: test
  tags:
    - hybrid-db
  script:
    - 'mvn clean verify -P with-integration-tests -DskipUTs -DintegrationTest.forkCount=1 -DConfigNodeMaxHeapSize=256 -DDataNodeMaxHeapSize=768 -DClusterConfigurations=$CLUSTER1,$CLUSTER2 -pl integration-test -am -PMultiClusterIT2DualTableManualBasic'
  parallel:
    matrix:
      - CLUSTER1: [HighPerformanceMode]
        CLUSTER2: [HighPerformanceMode]
  interruptible: true
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH 
        || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rel/ 
        || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rc/
        || $CI_PIPELINE_SOURCE == "schedule"
  artifacts:
    when: on_failure
    name: pipe-log-dual-table-manual-basic
    paths:
      - integration-test/target/cluster-logs
      - integration-test/target/pipeIT-logs
    expire_in: 7 day

pipe-dual-table-manual-enhanced:
  stage: test
  tags:
    - hybrid-db
  script:
    - 'mvn clean verify -P with-integration-tests -DskipUTs -DintegrationTest.forkCount=1 -DConfigNodeMaxHeapSize=256 -DDataNodeMaxHeapSize=768 -DClusterConfigurations=$CLUSTER1,$CLUSTER2 -pl integration-test -am -PMultiClusterIT2DualTableManualEnhanced'
  parallel:
    matrix:
      - CLUSTER1: [HighPerformanceMode]
        CLUSTER2: [HighPerformanceMode]
  interruptible: true
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH 
        || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rel/ 
        || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rc/
        || $CI_PIPELINE_SOURCE == "schedule"
  artifacts:
    when: on_failure
    name: pipe-log-dual-table-manual-enhanced
    paths:
      - integration-test/target/cluster-logs
      - integration-test/target/pipeIT-logs
    expire_in: 7 day

pipe-subscription:
  stage: test
  tags:
    - hybrid-db
  script:
    - 'mvn clean verify -P with-integration-tests -DskipUTs -DintegrationTest.forkCount=1 -DConfigNodeMaxHeapSize=256 -DDataNodeMaxHeapSize=768 -DClusterConfigurations=$CLUSTER1,$CLUSTER2 -pl integration-test -am -PMultiClusterIT2SubscriptionTreeArchVerification'
  parallel:
    matrix:
      - CLUSTER1: [HighPerformanceMode]
        CLUSTER2: [HighPerformanceMode]
  interruptible: true
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH 
        || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rel/ 
        || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rc/
        || $CI_PIPELINE_SOURCE == "schedule"
  artifacts:
    when: on_failure
    name: pipe-log-subscription
    paths:
      - integration-test/target/cluster-logs
      - integration-test/target/pipeIT-logs
    expire_in: 7 day

dependencies:
  stage: test
  tags:
    - hybrid-db
  script:
    - 'mvn verify -Dmaven.test.skip=true -Dmdep.analyze.skip=true -P enable-sbom-check'
  parallel:
    matrix:
      - CLUSTER1: [HighPerformanceMode]
        CLUSTER2: [HighPerformanceMode]
  interruptible: true
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH 
        || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rel/ 
        || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rc/
        || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "queryStage"
        || $CI_PIPELINE_SOURCE == "schedule"
sonarqube-check:
  stage: sonarqube-check
  tags:
    - hybrid-db
  script:
    - mvn clean verify sonar:sonar -Dsonar.projectKey=iotdb -Dsonar.projectName='iotdb' -Dsonar.host.url=http://192.168.134.103:9000 -Dsonar.login=squ_6c8818c6c18696ffbeadd31090714fa34085c276 $SONAR_SCAN_OPTS -DskipTests -pl '!example/jdbc,!example/mqtt,!example/mqtt-customize,!example/pipe-count-point-processor,!example/pipe-opc-ua-sink,!example/rest-java-example,!example/schema,!example/session,!example/trigger,!example/udf' -am
  allow_failure: true
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH 
        || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rel/ 
        || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rc/
        || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "queryStage"
        || $CI_PIPELINE_SOURCE == "schedule"
